services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.mysql:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8111:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./.wordpress:/var/www/html

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    ports:
        - "443:443"
        - "80:80"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./.caddy/data:/data
    environment:
        DOMAIN: wordpress.squadc.com
        BACKEND_API_URL: wordpress:80
